delete from dbo.AccelaCAPRecordStatus

insert into dbo.AccelaCAPRecordStatus (AccelaCAPRecordStatusID, AccelaCAPRecordStatusName, AccelaCAPRecordStatusDisplayName)
values
(1, 'Accepted', 'Accepted'),
(2, 'Issued', 'Issued'),
(3, 'ProjectCompleted', 'Project Completed'),
(4, 'Reviewed', 'Reviewed'),
(5, 'Withdrawn', 'Withdrawn'),
(6, 'Complete', 'Complete'),
(7, 'Concluded', 'Concluded'),
(8, 'WillCall', 'Will Call'),
(9, 'ResultsIssued', 'Results Issued'),
(10, 'Assigned', 'Assigned'),
(11, 'Incomplete', 'Incomplete'),
(12, 'InspectionRequired', 'Inspection Required'),
(13, 'Notes', 'Notes'),
(14, 'Denied', 'Denied'),
(15, 'Approved', 'Approved'),
(16, 'Expired', 'Expired'),
(17, 'Rescinded', 'Rescinded'),
(18, 'InReview', 'In Review'),
(19, 'IncompleteSubmittal', 'Incomplete Submittal'),
(20, 'ConditionalPermit', 'Conditional Permit'),
(21, 'HoldPerApplicant', 'Hold Per Applicant'),
(22, 'SnowHold', 'Snow Hold'),
(23, 'LegalTolling', 'Legal Tolling'),
(24, 'Acknowledged', 'Acknowledged'),
(25, 'MonitoringComplete', 'Monitoring Complete'),
(26, 'FinalInspectionComplete', 'Final Inspection Complete'),
(27, 'ConstructionExtension', 'Construction Extension'),
(28, 'ProjectSecurityReleased', 'Project Security Released'),
(29, 'ScenicSecurityReleased', 'Scenic Security Released'),
(30, 'OtherSecurityReleased', 'Other Security Released'),
(31, 'AdditionalInformation', 'Additional Information'),
(32, 'ReviewFinished', 'Review Finished'),
(33, 'DeterminationIssued', 'Determination Issued'),
(34, 'OTCDeterminationIssued', 'OTC Determination Issued'),
(35, 'TRPAReviewFinished', 'TRPA Review Finished'),
(36, 'SHPOResponseReceived', 'SHPO Response Received'),
(37, 'RequestForCommentSubmitted', 'Request for Comment Submitted'),
(38, 'NotRequired', 'Not Required'),
(39, 'ApplicationReceived', 'Application Received'),
(40, 'Received', 'Received'),
(41, 'Acknowlefged', 'Acknowlefged'),
(42, 'CertUpdated', 'Cert Updated'),
(43, 'Certified', 'Certified'),
(44, 'Closed', 'Closed'),
(45, 'DeterOpinionIssued', 'Deter/Opinion Issued'),
(46, 'Finaled', 'Finaled'),
(47, 'Granted', 'Granted'),
(48, 'Initiated', 'Initiated'),
(49, 'LossOfExemption', 'Loss of Exemption'),
(50, 'Negotiation', 'Negotiation'),
(51, 'NonCompliance', 'Non-Compliance'),
(52, 'NoticeIssued', 'Notice Issued'),
(53, 'Ongoing', 'Ongoing'),
(54, 'Qualified', 'Qualified'),
(55, 'Referred', 'Referred'),
(56, 'ReferredToVRU', 'Referred to VRU'),
(57, 'Rejected', 'Rejected'),
(58, 'Released', 'Released'),
(59, 'Resolved', 'Resolved'),
(60, 'Responded', 'Responded'),
(61, 'ReviewedStaff', 'Reviewed-Staff'),
(62, 'Revised', 'Revised'),
(63, 'SettlementAccepted', 'Settlement Accepted'),
(64, 'SettlementApproved', 'Settlement Approved'),
(65, 'Stayed', 'Stayed'),
(66, 'Appealed', 'Appealed'),
(67, 'Archived', 'Archived'),
(68, 'AwaitingAssignment', 'Awaiting Assignment'),
(69, 'CertifiedAdopted', 'Certified/Adopted'),
(70, 'ComplaintFiled', 'Complaint Filed'),
(71, 'Consulted', 'Consulted'),
(72, 'Continued', 'Continued'),
(73, 'Continuing', 'Continuing'),
(74, 'Decision', 'Decision'),
(75, 'DEISAdequate', 'DEIS Adequate'),
(76, 'DEISInRevision', 'DEIS in Revision'),
(77, 'DeterminationOpinionIssued', 'Determination/Opinion Issued'),
(78, 'Done', 'Done'),
(79, 'Dropped', 'Dropped'),
(80, 'EAComplete', 'EA Complete'),
(81, 'Federal', 'Federal'),
(82, 'FinalInspection', 'Final Inspection'),
(83, 'FinalInspectionCompleted', 'Final Inspection Completed'),
(84, 'Hold', 'Hold'),
(85, 'HoldForApplicant', 'Hold For Applicant'),
(86, 'Implemented', 'Implemented'),
(87, 'InDraft', 'In Draft'),
(88, 'Inspected', 'Inspected'),
(89, 'InspectionInProcess', 'Inspection In Process'),
(90, 'Litigate', 'Litigate'),
(91, 'NoResponse', 'No Response'),
(92, 'NoViolation', 'No Violation'),
(93, 'NotQualified', 'Not Qualified'),
(94, 'NoticeSent', 'Notice Sent'),
(95, 'Noticed', 'Noticed'),
(96, 'OnHold', 'On Hold'),
(97, 'PassedEval', 'Passed Eval'),
(98, 'PermitFinaled', 'Permit Finaled'),
(99, 'PermitRequired', 'Permit Required'),
(100, 'Permitted', 'Permitted'),
(101, 'PlannerReviewFinished', 'Planner Review Finished'),
(102, 'ReferredToERS', 'Referred to ERS'),
(103, 'ReferredToMOU', 'Referred to MOU'),
(104, 'ResolutionSettlement', 'RESOLUTION/SETTLEMENT'),
(105, 'ReviewedStaffWithComma', 'Reviewed, Staff'),
(106, 'RevisedAccepted', 'Revised Accepted'),
(107, 'ScopeCirculated', 'Scope Circulated'),
(108, 'Scoped', 'Scoped'),
(109, 'SettlementDeclined', 'Settlement Declined'),
(110, 'UnderReview', 'Under Review'),
(111, 'UnpaidFees', 'Unpaid Fees'),
(112, 'Violation', 'Violation'),
(113, 'Void', 'Void')

