delete from dbo.LeadAgencyTransactionTypeCommodityLogChangeType
go

insert into dbo.LeadAgencyTransactionTypeCommodityLogChangeType(LeadAgencyTransactionTypeCommodityLogChangeTypeID, LeadAgencyTransactionTypeCommodityLogChangeTypeName, LeadAgencyTransactionTypeCommodityLogChangeTypeDisplayName) values(1, 'Added', 'Added')
insert into dbo.LeadAgencyTransactionTypeCommodityLogChangeType(LeadAgencyTransactionTypeCommodityLogChangeTypeID, LeadAgencyTransactionTypeCommodityLogChangeTypeName, LeadAgencyTransactionTypeCommodityLogChangeTypeDisplayName) values(2, 'Removed', 'Removed')
