delete from dbo.FieldDefinition
go

insert into dbo.FieldDefinition(FieldDefinitionID, FieldDefinitionDisplayName, FieldDefinitionName, DefaultDefinition) 
values
(1, 'Taxonomy Tier One', 'TaxonomyTierOne', null),
(4, 'Expected Value', 'ExpectedValue', null),
(5, 'Taxonomy Tier Three', 'TaxonomyTierThree', null),
(7, 'Funder', 'Funder', null),
(8, 'Funding Source', 'FundingSource', null),
(11, 'Implementer', 'Implementer', null),
(12, 'Lead Implementer', 'LeadImplementer', null),
(14, 'Organization', 'Organization', null),
(17, 'Password', 'Password', null),
(18, 'Performance Measure', 'PerformanceMeasure', null),
(19, 'Performance Measure Type', 'PerformanceMeasureType', null),
(21, 'Measurement Unit', 'MeasurementUnit', null),
(22, 'Photo Caption', 'PhotoCaption', null),
(23, 'Photo Credit', 'PhotoCredit', null),
(24, 'Photo Timing', 'PhotoTiming', null),
(25, 'Primary Contact', 'PrimaryContact', null),
(26, 'Taxonomy Tier Two', 'TaxonomyTierTwo', null),
(28, 'Completion Year', 'CompletionYear', null),
(29, 'Project Description', 'ProjectDescription', null),
(30, 'Project Name', 'ProjectName', null),
(31, 'Project Note', 'ProjectNote', null),
(32, 'Implementation Start Year', 'ImplementationStartYear', null),
(33, 'Reported Value', 'ReportedValue', null),
(34, 'Sector', 'Sector', null),
(35, 'Secured Funding', 'SecuredFunding', null),
(36, 'Project Stage', 'ProjectStage', null),
(39, 'Classification Name', 'ClassificationName', null),
(40, 'Estimated Total Cost', 'EstimatedTotalCost', null),
(41, 'Unfunded Need', 'UnfundedNeed', null),
(42, 'User name', 'Username', null),
(44, 'Project', 'Project', null),
(46, 'Classification', 'Classification', null),
(48, 'Watershed', 'Watershed', null),
(49, 'Performance Measure Subcategory', 'PerformanceMeasureSubcategory', null),
(50, 'Performance Measure Subcategory Option', 'PerformanceMeasureSubcategoryOption', null),
(52, 'Is Primary Taxonomy Tier Two', 'IsPrimaryTaxonomyTierTwo', null),
(56, 'Funded Amount', 'FundedAmount', null),
(57, 'Project Location', 'ProjectLocation', null),
(64, 'Exclude from Fact Sheet', 'ExcludeFromFactSheet', null),
(73, 'Funding Type', 'FundingType', null),
(74, 'Cost in Year of Expenditure', 'ProjectCostInYearOfExpenditure', null),
(75, 'Global Inflation Rate', 'GlobalInflationRate', null),
(76, 'Reporting Year', 'ReportingYear', null),
(77, 'Tag Name', 'TagName', null),
(78, 'Tag Description', 'TagDescription', null),
(80, 'Reported Expenditure', 'ReportedExpenditure', null),
(81, 'Proposed Project', 'ProposedProject', null),
(85, 'Spending Associated with PM', 'SpendingAssociatedWithPM', null),
(86, 'Planning / Design Start Year', 'PlanningDesignStartYear', null),
(87, 'Associated TaxonomyTierTwos', 'AssociatedTaxonomyTierTwos', null),
(88, 'External Links', 'ExternalLinks', null),
(89, 'Est. Annual Operating Cost', 'EstimatedAnnualOperatingCost', null),
(90, 'Remaining Operating Cost', 'CalculatedTotalRemainingOperatingCost', null),
(91, 'Current Year for PV Calculations', 'CurrentYearForPVCalculations', null),
(92, 'Lifecycle Operating Cost', 'LifecycleOperatingCost', null),
(97, 'Performance Measure Chart Title', 'PerformanceMeasureChartTitle', null),
(182, 'Role Name', 'RoleName', null),
(184, 'Region (Geospatial, null),', 'Region', null),
(228, 'Performance Measure Chart Caption', 'PerformanceMeasureChartCaption', null),
(236, 'Monitoring Program', 'MonitoringProgram', null),
(237, 'Monitoring Approach', 'MonitoringApproach', null),
(238, 'Monitoring Program Partner', 'MonitoringProgramPartner', null),
(239, 'Monitoring Program Home Page', 'MonitoringProgramUrl', null),
(240, 'Classification Description', 'ClassificationDescription', null),
(241, 'Classification Goal Statement', 'ClassificationGoalStatement', null),
(242, 'Classification Narrative', 'ClassificationNarrative', null)
