delete from dbo.FirmaPageType
go

insert into dbo.FirmaPageType(FirmaPageTypeID, FirmaPageTypeName, FirmaPageTypeDisplayName, FirmaPageRenderTypeID)
values
(1, 'HomePage', 'Home Page', 2),
(2, 'About', 'About Clackamas Partnership', 2),
(3, 'FirmaCustomPage1', 'Meetings and Documents', 2),
(4, 'FirmaCustomPage2', 'Firma Custom Page 2', 2),
(5, 'FirmaCustomPage3', 'Firma Custom Page 3', 2),
(6, 'FullProjectList', 'Full Project List', 1),
(7, 'FiveYearProjectList', '5 Year Project List', 1),
(8, 'CompletedProjectList', 'Completed Project List', 1),
(9, 'PerformanceMeasuresList', 'Performance Measures List', 1),
(11, 'ActionPrioritiesList', 'Action Priorities List', 1),
(12, 'LocalAndRegionalPlansList', 'Local and Regional Plans List', 1),
(13, 'FocusAreasList', 'Focus Areas List', 1),
(14, 'FundingSourcesList', 'Funding Sources List', 1),
(15, 'OrganizationsList', 'Organizations List', 1),
(16, 'ProgramsList', 'Programs List', 1),
(17, 'WatershedsList', 'Watersheds List', 1),
(18, 'MyProjects', 'My Projects', 1),
(19, 'PagesWithIntroTextList', 'Manage Introductory Text for Pages', 1),
(20, 'InvestmentByFundingSector', 'Investment by Funding Sector', 1),
(21, 'SpendingBySectorByFocusAreaByProgram', 'Spending by Sector by Focus Area by Program', 1),
(22, 'ProjectMap', 'Project Map', 1),
(23, 'ResultsByProgram', 'Results by Program', 1),
(25, 'HomeAdditionalInfo', 'Home Page Additional Info', 2),
(26, 'FeaturedProjectList', 'Featured Project List', 1),
(31, 'CostParameterSet', 'Cost Parameter Set', 1),
(32, 'TerminatedProjectList', 'Terminated Project List', 1),
(33, 'FullProjectListSimple', 'Full Project List (Simple)', 1),
(34, 'Taxonomy', 'Taxonomy', 1),
(36, 'TagList', 'Tag List', 1),
(37, 'SpendingByPerformanceMeasureByProject', 'Spending by Performance Measure by Project', 1),
(38, 'ProposedProjects', 'Proposed Projects', 1),
(39, 'MyOrganizationsProjects', 'My Organization''s Projects', 1),
(41, 'ManageUpdateNotifications', 'Manage Project Update Notifications', 1),
(42, 'ProjectUpdateStatus', 'Annual Project Update Status Report', 1),
(66, 'ThresholdCategoriesList', 'Threshold Categories List', 1),
(67, 'MonitoringProgramsList', 'Monitoring Programs', 1)
