delete from dbo.ProjectFirmaPageType
go

insert into dbo.ProjectFirmaPageType(ProjectFirmaPageTypeID, ProjectFirmaPageTypeName, ProjectFirmaPageTypeDisplayName, PrimaryLTInfoAreaID, ProjectFirmaPageRenderTypeID)
values
(1, 'HomePage', 'Home Page', 1, 2),
(2, 'AboutClackamasPartnership', 'About Clackamas Partnership', 1, 2),
(3, 'Meetings', 'Meetings', 1, 2),
(6, 'FullProjectList', 'Full Project List', 1, 1),
(7, 'FiveYearProjectList', '5 Year Project List', 1, 1),
(8, 'CompletedProjectList', 'Completed Project List', 1, 1),
(9, 'EIPPerformanceMeasuresList', 'EIP Performance Measures List', 1, 1),
(11, 'ActionPrioritiesList', 'Action Priorities List', 1, 1),
(12, 'LocalAndRegionalPlansList', 'Local and Regional Plans List', 1, 1),
(13, 'FocusAreasList', 'Focus Areas List', 1, 1),
(14, 'FundingSourcesList', 'Funding Sources List', 1, 1),
(15, 'OrganizationsList', 'Organizations List', 1, 1),
(16, 'ProgramsList', 'Programs List', 1, 1),
(17, 'WatershedsList', 'Watersheds List', 1, 1),
(18, 'MyProjects', 'My Projects', 1, 1),
(19, 'PagesWithIntroTextList', 'Manage Introductory Text for Pages', 1, 1),
(20, 'InvestmentByFundingSector', 'EIP Investment by Funding Sector', 1, 1),
(21, 'SpendingBySectorByFocusAreaByProgram', 'Spending by Sector by Focus Area by Program', 1, 1),
(22, 'EIPProjectMap', 'EIP Project Map', 1, 1),
(23, 'EIPResultsByProgram', 'EIP Results by Program', 1, 1),
(25, 'EIPHomeAdditionalInfo', 'EIP Tracker Home Page Additional Info', 1, 2),
(26, 'FeaturedProjectList', 'Featured Project List', 1, 1),
(28, 'TransportationStrategiesList', 'Transportation Strategies List', 1, 1),
(29, 'TransportationObjectivesList', 'Transportation Objectives List', 1, 1),
(30, 'TransportationProjectList', 'Transportation Project List', 1, 1),
(31, 'TransportationCostParameterSet', 'Transportation Cost Parameter Set', 1, 1),
(32, 'TerminatedProjectList', 'Terminated Project List', 1, 1),
(33, 'FullProjectListSimple', 'Full Project List (Simple)', 1, 1),
(34, 'EIPTaxonomy', 'EIP Taxonomy', 1, 1),
(35, 'TransportationTaxonomy', 'Transportation Strategies and Objectives', 1, 1),
(36, 'TagList', 'Tag List', 1, 1),
(37, 'SpendingByEIPPerformanceMeasureByProject', 'Spending by Performance Measure by Project', 1, 1),
(38, 'ProposedProjects', 'Proposed Projects', 1, 1),
(39, 'MyOrganizationsProjects', 'My Organization''s Projects', 1, 1),
(41, 'ManageUpdateNotifications', 'Manage Project Update Notifications', 1, 1),
(42, 'ProjectUpdateStatus', 'Annual Project Update Status Report', 1, 1),
(66, 'ThresholdCategoriesList', 'Threshold Categories List', 1, 1),
(67, 'MonitoringProgramsList', 'Monitoring Programs', 1, 1)