import { IEventSystem } from "../../ts-common/events";
import { View } from "../../ts-common/view";
import { DataCollection, DataEvents, IDataEventsHandlersMap } from "../../ts-data";
import { List } from "../../ts-list";
import { Popup } from "../../ts-popup";
import { ComboboxEvents, ICombobox, IComboboxConfig, IComboboxEventHandlersMap, State } from "./types";
export declare class Combobox extends View implements ICombobox {
    data: DataCollection;
    config: IComboboxConfig;
    events: IEventSystem<DataEvents | ComboboxEvents, IComboboxEventHandlersMap | IDataEventsHandlersMap>;
    list: List;
    popup: Popup;
    protected _helper: Popup;
    private _keyListener;
    private _layout;
    private _state;
    private _handlers;
    constructor(element: HTMLElement | string, config: IComboboxConfig);
    focus(): boolean;
    enable(): void;
    disable(): void;
    isDisabled(): boolean;
    clear(): boolean;
    getValue<T extends boolean = false>(asArray?: T): T extends true ? string[] : string;
    setValue(ids: string[] | string): boolean;
    destructor(): void;
    setState(state: State): void;
    private _createLayout;
    private _initHandlers;
    private _initEvents;
    private _showOptions;
    private _configurePopup;
    private _hideOptions;
    private _filter;
    private _findBest;
    private _draw;
    private _drawSelectedItems;
    private _drawImageOrIcon;
    private _getItemText;
    private _updateSelectedItem;
}
