alter table ProjectFundingSourceExpenditure
drop constraint CK_ProjectFundingSourceExpenditure_ExpenditureAmountWholeDollarOnlyNoCents

alter table ProjectFundingSourceExpenditureUpdate
drop constraint CK_ProjectFundingSourceExpenditureUpdate_ExpenditureAmountWholeDollarOnlyNoCents