alter table dbo.ProjectFundingSourceExpenditure
drop constraint CK_ProjectFundingSourceExpenditure_ExpenditureAmountWholeDollarOnlyNoCents

alter table dbo.ProjectFundingSourceExpenditureUpdate
drop constraint CK_ProjectFundingSourceExpenditureUpdate_ExpenditureAmountWholeDollarOnlyNoCents

alter table dbo.ProjectFundingSourceRequest
drop constraint CK_ProjectFundingSourceRequest_UnsecuredAmountWholeDollarOnlyNoCents