insert into dbo.TrainingVideo (TenantID, VideoName, VideoDescription, VideoUploadDate, VideoURL)
values
(7, 'Complete Admin Training', 'This is the John Day Basin Partnership Project Tracker Admin Training presented by Liz Christeleit and Kathleen Elmquist on 2/18/20.', CONVERT(date, getdate()), 'https://youtube.com/embed/HekP9QmfV-M'),
(7, 'Admin Training – Available Resources', 'This is the Available Resources section of the John Day Basin Partnership Project Tracker Admin Training presented by Liz Christeleit and Kathleen Elmquist on 2/18/20.', CONVERT(date, getdate()), 'https://youtube.com/embed/9tQogESAg5s'),
(7, 'Admin Training – User Account Management', 'This is the User Account Management section of the John Day Basin Partnership Project Tracker Admin Training presented by Liz Christeleit and Kathleen Elmquist on 2/18/20.', CONVERT(date, getdate()), 'https://youtube.com/embed/e5qugH-DSOY'),
(7, 'Admin Training – Proposal/Pending Project Approval Process', 'This is the Proposal/Pending Project Approval Process section of the John Day Basin Partnership Project Tracker Admin Training presented by Liz Christeleit and Kathleen Elmquist on 2/18/20', CONVERT(date, getdate()), 'https://youtube.com/embed/i1nb9P6cqvo'),
(7, 'Admin Training – Project Update Approvals', 'This is the Project Update Approvals section of the John Day Basin Partnership Project Tracker Admin Training presented by Liz Christeleit and Kathleen Elmquist on 2/18/20.', CONVERT(date, getdate()), 'https://youtube.com/embed/90FH6WCOdWo'),
(7, 'Admin Training – Organization & Funding Sources Management', 'This is the Organization & Funding Sources Management section of the John Day Basin Partnership Project Tracker Admin Training presented by Liz Christeleit and Kathleen Elmquist on 2/18/20.', CONVERT(date, getdate()), 'https://youtube.com/embed/_H0Et1ugpOA'),
(7, 'Admin Training – Adding a Page to the About Menu', 'This is the Adding a Page to the About Menu section of the John Day Basin Partnership Project Tracker Admin Training presented by Liz Christeleit and Kathleen Elmquist on 2/18/20.', CONVERT(date, getdate()), 'https://youtube.com/embed/9RjoMJSWFy8'),
(7, 'Admin Training – Configuring Definitions', 'This is the Configuring Definitions section of the John Day Basin Partnership Project Tracker Admin Training presented by Liz Christeleit and Kathleen Elmquist on 2/18/20.', CONVERT(date, getdate()), 'https://youtube.com/embed/z3nafbesVsE')
