alter table dbo.ProjectCustomAttributeType drop constraint AK_ProjectCustomAttributeType_ProjectCustomAttributeTypeName 

alter table dbo.ProjectCustomAttributeType add constraint AK_ProjectCustomAttributeType_ProjectCustomAttributeTypeName_TenantID unique (ProjectCustomAttributeTypeName, TenantID)

alter table dbo.FundingSourceCustomAttributeType drop constraint AK_FundingSourceCustomAttributeType_FundingSourceCustomAttributeTypeName 

alter table dbo.FundingSourceCustomAttributeType add constraint AK_FundingSourceCustomAttributeType_FundingSourceCustomAttributeTypeName_TenantID unique (FundingSourceCustomAttributeTypeName, TenantID)