
insert into dbo.OrganizationType (TenantID, OrganizationTypeName, OrganizationTypeAbbreviation, LegendColor, ShowOnProjectMaps, IsDefaultOrganizationType, IsFundingType, LayerOnByDefault)
values
(4, 'Fire Safe Council', 'FSC', '#f5a500', 0, 0, 0, 0),
(4, 'Fire Protection District/ Fire District', 'FPD/FD', '#ee8b83', 0, 0, 0, 0)

insert into dbo.[ProjectCustomAttributeType] (TenantID, ProjectCustomAttributeTypeName, ProjectCustomAttributeDataTypeID, IsRequired, IsViewableOnFactSheet, ProjectCustomAttributeGroupID)
values
(4, 'CALFIRE Unit', 1, 0, 0, 22),
(4, 'Project Area', 1, 0, 0, 22)

-- both new custom attributes are viewable by and editable by all roles
insert into dbo.ProjectCustomAttributeTypeRole (TenantID, ProjectCustomAttributeTypeID, RoleID, ProjectCustomAttributeTypeRolePermissionTypeID)
values
(4, (select ProjectCustomAttributeTypeID from dbo.ProjectCustomAttributeType where TenantID = 4 and ProjectCustomAttributeTypeName = 'CALFIRE Unit'), 2, 1),
(4, (select ProjectCustomAttributeTypeID from dbo.ProjectCustomAttributeType where TenantID = 4 and ProjectCustomAttributeTypeName = 'CALFIRE Unit'), 7, 1),
(4, (select ProjectCustomAttributeTypeID from dbo.ProjectCustomAttributeType where TenantID = 4 and ProjectCustomAttributeTypeName = 'CALFIRE Unit'), 9, 1),
(4, (select ProjectCustomAttributeTypeID from dbo.ProjectCustomAttributeType where TenantID = 4 and ProjectCustomAttributeTypeName = 'CALFIRE Unit'), 2, 2),
(4, (select ProjectCustomAttributeTypeID from dbo.ProjectCustomAttributeType where TenantID = 4 and ProjectCustomAttributeTypeName = 'CALFIRE Unit'), 7, 2),
(4, (select ProjectCustomAttributeTypeID from dbo.ProjectCustomAttributeType where TenantID = 4 and ProjectCustomAttributeTypeName = 'CALFIRE Unit'), 9, 2),
(4, (select ProjectCustomAttributeTypeID from dbo.ProjectCustomAttributeType where TenantID = 4 and ProjectCustomAttributeTypeName = 'Project Area'), 2, 1),
(4, (select ProjectCustomAttributeTypeID from dbo.ProjectCustomAttributeType where TenantID = 4 and ProjectCustomAttributeTypeName = 'Project Area'), 7, 1),
(4, (select ProjectCustomAttributeTypeID from dbo.ProjectCustomAttributeType where TenantID = 4 and ProjectCustomAttributeTypeName = 'Project Area'), 9, 1),
(4, (select ProjectCustomAttributeTypeID from dbo.ProjectCustomAttributeType where TenantID = 4 and ProjectCustomAttributeTypeName = 'Project Area'), 2, 2),
(4, (select ProjectCustomAttributeTypeID from dbo.ProjectCustomAttributeType where TenantID = 4 and ProjectCustomAttributeTypeName = 'Project Area'), 7, 2),
(4, (select ProjectCustomAttributeTypeID from dbo.ProjectCustomAttributeType where TenantID = 4 and ProjectCustomAttributeTypeName = 'Project Area'), 9, 2)

insert into dbo.Organization (TenantID, OrganizationName, OrganizationShortName, OrganizationTypeID, IsActive, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified)
values
(4, 'Albion Fire', 'Albion Fire', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Protection District/ Fire District'), 1, 0, 0),
(4, 'Anderson Valley Fire District', 'Anderson Valley FD', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Protection District/ Fire District'), 1, 0, 0),
(4, 'Audubon Canyon Ranch- Bouverie Preserve', 'Audubon Canyon Ranch- Bouverie Preserve', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Non-Profit Organization'), 1, 0, 0),
(4, 'Baseline Consulting', 'Baseline Consulting', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Private'), 1, 0, 0),
(4, 'Bell Springs Fire District', 'Bell Springs FD', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Protection District/ Fire District'), 1, 0, 0),
(4, 'Bennett Ridge Fire Safety Organization', 'Bennett Ridge Fire Safety Organization', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Other'), 1, 0, 0),
(4, 'Black Bart Fire Safe Council', 'Black Bart FSC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Safe Council'), 1, 0, 0),
(4, 'Brooktrails Fire Department', 'Brooktrails Fire Department', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Protection District/ Fire District'), 1, 0, 0),
(4, 'Cahto Tribe', 'Cahto Tribe', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Federally Recognized Indian Tribe'), 1, 0, 0),
(4, 'California Deer Association', 'California Deer Association', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Non-Profit Organization'), 1, 0, 0),
(4, 'California Dept of Transportation', 'California Dept of Transportation', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'State Agency'), 1, 0, 0),
(4, 'Camp Meeker Fire Safe Council', 'Camp Meeker FSC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Safe Council'), 1, 0, 0),
(4, 'Caspar Community', 'Caspar Community', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Other'), 1, 0, 0),
(4, 'Cazadero Community Services District', 'Cazadero Community Services District', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Public Agency'), 1, 0, 0),
(4, 'California Conservation Corps', 'California Conservation Corps', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'State Agency'), 1, 0, 0),
(4, 'City of Arcata', 'City of Arcata', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'City or Town'), 1, 0, 0),
(4, 'City of Healdsburg Fire', 'City of Healdsburg Fire', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'City or Town'), 1, 0, 0),
(4, 'Cloverdale Fire Protection District', 'Cloverdale Fire Protection District', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Protection District/ Fire District'), 1, 0, 0),
(4, 'Coastal Forestlands Ltd', 'Coastal Forestlands Ltd', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Private'), 1, 0, 0),
(4, 'Collins Timber Company LLC', 'Collins Timber Company LLC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Private'), 1, 0, 0),
(4, 'Crooked Prairie Fire Safe Council', 'Crooked Prairie FSC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Safe Council'), 1, 0, 0),
(4, 'Cultural Fire Management Council', 'Cultural Fire Management Council', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Other'), 1, 0, 0),
(4, 'Comptche Volunteer Fire Department', 'Comptche Volunteer Fire Department', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Protection District/ Fire District'), 1, 0, 0),
(4, 'Del Norte Fire Safe Council', 'Del Norte FSC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Safe Council'), 1, 0, 0),
(4, 'Ecotrust Forests II', 'Ecotrust Forests II', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Non-Profit Organization'), 1, 0, 0),
(4, 'Elk County School District', 'Elk County School District', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Public Agency'), 1, 0, 0),
(4, 'Elk Community Services District', 'Elk Community Services District', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Public Agency'), 1, 0, 0),
(4, 'FireSafe Sonoma', 'FireSafe Sonoma', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Safe Council'), 1, 0, 0),
(4, 'Fitch Mountain COPE', 'Fitch Mountain COPE', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Other'), 1, 0, 0),
(4, 'Fort Bragg Fire Department', 'Fort Bragg Fire Department', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Protection District/ Fire District'), 1, 0, 0),
(4, 'Fort Ross Fire District', 'Fort Ross FD', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Protection District/ Fire District'), 1, 0, 0),
(4, 'Friends of Rio Nido', 'Friends of Rio Nido', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Other'), 1, 0, 0),
(4, 'Friends of Upper Mark West Creek', 'Friends of Upper Mark West Creek', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Other'), 1, 0, 0),
(4, 'Fruit Growers Supply Company', 'Fruit Growers Supply Company', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Private'), 1, 0, 0),
(4, 'Greater Lake Shastina Fire Safe Council', 'Greater Lake Shastina FSC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Protection District/ Fire District'), 1, 0, 0),
(4, 'Hammond Ranch Fire Safe Council', 'Hammond Ranch FSC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Safe Council'), 1, 0, 0),
(4, 'Happy Camp Fire Safe Council', 'Happy Camp FSC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Safe Council'), 1, 0, 0),
(4, 'Human Services', 'Human Services', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Other'), 1, 0, 0),
(4, 'Humboldt State University Sponsored Programs Foundation', 'HSU Sponsored Programs Foundation', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'State Agency'), 1, 0, 0),
(4, 'Juniper Flat Fire Safe Council', 'Juniper Flat FSC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Safe Council'), 1, 0, 0),
(4, 'Klamath National Forest', 'Klamath National Forest', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Federal Agency'), 1, 0, 0),
(4, 'Klamath National Forest Goosenest Ranger District', 'KNF Goosenest RD', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Federal Agency'), 1, 0, 0),
(4, 'Lake Shastina Property Owners'' Association', 'Lake Shastina POA', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Other'), 1, 0, 0),
(4, 'Landowner Association', 'Landowner Assn.', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Other'), 1, 0, 0),
(4, 'LandPaths', 'LandPaths', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Non-Profit Organization'), 1, 0, 0),
(4, 'Laytonville Fire Department (LFire District)', 'Laytonville Fire Department (LFD)', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Protection District/ Fire District'), 1, 0, 0),
(4, 'Lower Mattole Fire Safe Council', 'Lower Mattole FSC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Safe Council'), 1, 0, 0),
(4, 'Mayacamas Fire Safe Council', 'Mayacamas FSC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Safe Council'), 1, 0, 0),
(4, 'Mendocino Ag Dept', 'Mendocino Ag Dept', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Local Agency'), 1, 0, 0),
(4, 'Mendocino County', 'Mendocino County', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Local Agency'), 1, 0, 0),
(4, 'Mendocino County Fire Safe Council', 'Mendocino County FSC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Safe Council'), 1, 0, 0),
(4, 'Mendocino Fire District', 'Mendocino FD', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Protection District/ Fire District'), 1, 0, 0),
(4, 'Mill Creek CWPP Planning Group and Steering Committee', 'Mill Creek CWPP PlanningGroup & SteeringCommittee', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Other'), 1, 0, 0),
(4, 'Modoc County Fire Safe Council', 'Modoc County FSC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Safe Council'), 1, 0, 0),
(4, 'Modoc County Road Department', 'Modoc County Road Department', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Local Agency'), 1, 0, 0),
(4, 'Muniz Ranches Property Owners Association', 'Muniz Ranches Property Owners Association', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Other'), 1, 0, 0),
(4, 'Mendocino Volunteer Fire Department', 'Mendocino Volunteer Fire Department', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Protection District/ Fire District'), 1, 0, 0),
(4, 'National Fish and Wildlife Foundation', 'National Fish and Wildlife Foundation', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Non-Profit Organization'), 1, 0, 0),
(4, 'North Coast Regional Land Trust', 'North Coast Regional Land Trust', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Non-Profit Organization'), 1, 0, 0),
(4, 'North Coast Resource Center', 'North Coast Resource Center', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Other'), 1, 0, 0),
(4, 'Northern California Resource Center', 'Northern California Resource Center', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Non-Profit Organization'), 1, 0, 0),
(4, 'Occidental Fire Safe Council', 'Occidental FSC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Safe Council'), 1, 0, 0),
(4, 'ORE-CAL RCDC', 'ORE-CAL RCDC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Non-Profit Organization'), 1, 0, 0),
(4, 'Orleans Somes Bar Fire Safe Council', 'Orleans Somes Bar FSC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Safe Council'), 1, 0, 0),
(4, 'Orleans Volunteer Fire Department', 'Orleans Volunteer Fire Department', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Protection District/ Fire District'), 1, 0, 0),
(4, 'Pepperwood Preserve', 'Pepperwood Preserve', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Non-Profit Organization'), 1, 0, 0),
(4, 'Permit Sonoma', 'Permit Sonoma', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Local Agency'), 1, 0, 0),
(4, 'Pit Resource Conservation District', 'Pit Resource Conservation District', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Resource Conservation District'), 1, 0, 0),
(4, 'Petrolia Volunteer Fire Department', 'Petrolia Volunteer Fire Department', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Protection District/ Fire District'), 1, 0, 0),
(4, 'Red Cross', 'Red Cross', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Non-Profit Organization'), 1, 0, 0),
(4, 'Redwood Valley Band of Pomo Indians', 'Redwood Valley Band of Pomo Indians', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Federally Recognized Indian Tribe'), 1, 0, 0),
(4, 'Renewable Energy Development Institute dba Sherwood Firewise', 'REDI dba Sherwood Firewise', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Other'), 1, 0, 0),
(4, 'Resort Improvement District No. 1', 'Resort Improvement District No. 1', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Local Agency'), 1, 0, 0),
(4, 'Redwood Forest Foundation, Inc.', 'Redwood Forest Foundation, Inc.', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Private'), 1, 0, 0),
(4, 'Robinson Creek Fire Safe Council', 'Robinson Creek FSC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Safe Council'), 1, 0, 0),
(4, 'Rolling Hills Water Department', 'Rolling Hills Water Department', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Other'), 1, 0, 0),
(4, 'Santa Rosa Junior College', 'Santa Rosa Junior College', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Local Agency'), 1, 0, 0),
(4, 'Save the Redwoods League', 'Save the Redwoods League', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Non-Profit Organization'), 1, 0, 0),
(4, 'Scott Bar Fire Safe Council', 'Scott Bar FSC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Safe Council'), 1, 0, 0),
(4, 'Scott Valley Fire Protection District', 'Scott Valley Fire Protection District', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Protection District/ Fire District'), 1, 0, 0),
(4, 'Sea Ranch', 'Sea Ranch', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Private'), 1, 0, 0),
(4, 'Sea Ranch Fire Safe Council', 'Sea Ranch FSC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Safe Council'), 1, 0, 0),
(4, 'Seiad Valley Fire Safe Council', 'Seiad Valley FSC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Safe Council'), 1, 0, 0),
(4, 'Seiad Valley Volunteer Fire Co.', 'Seiad Valley Volunteer Fire Co.', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Protection District/ Fire District'), 1, 0, 0),
(4, 'Shafer Ranch Road Association', 'Shafer Ranch Road Association', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Other'), 1, 0, 0),
(4, 'Shasta Ranch Road Association', 'Shasta Ranch Road Association', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Other'), 1, 0, 0),
(4, 'Siskiyou County Fire Safe Council', 'Siskiyou County FSC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Safe Council'), 1, 0, 0),
(4, 'Six Rivers National Forest', 'Six Rivers National Forest', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Federal Agency'), 1, 0, 0),
(4, 'Sonoma Biochar Initiative at Sonoma Ecology Center', 'Sonoma Biochar Initiative at Sonoma Ecology Center', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Other'), 1, 0, 0),
(4, 'Sonoma Land Trust', 'Sonoma Land Trust', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Non-Profit Organization'), 1, 0, 0),
(4, 'Sonoma State University', 'Sonoma State University', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'State Agency'), 1, 0, 0),
(4, 'Sonoma Water', 'Sonoma Water', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Local Agency'), 1, 0, 0),
(4, 'State Parks', 'State Parks', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'State Agency'), 1, 0, 0),
(4, 'State Parks Fox Camp', 'State Parks Fox Camp', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Other'), 1, 0, 0),
(4, 'Student Conservation Assoc', 'Student Conservation Assoc', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Other'), 1, 0, 0),
(4, 'The Conservation Fund', 'The Conservation Fund', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Non-Profit Organization'), 1, 0, 0),
(4, 'The Nature Conservancy', 'The Nature Conservancy', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Non-Profit Organization'), 1, 0, 0),
(4, 'The Sea Ranch Fire Safe Council', 'The Sea Ranch FSC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Safe Council'), 1, 0, 0),
(4, 'The Six Rivers Initiative', 'The Six Rivers Initiative', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Non-Profit Organization'), 1, 0, 0),
(4, 'The Trust for Public Land', 'The Trust for Public Land', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Non-Profit Organization'), 1, 0, 0),
(4, 'The Wildlands Conservancy', 'The Wildlands Conservancy', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Non-Profit Organization'), 1, 0, 0),
(4, 'Timber Cove Water Company', 'Timber Cove Water Company', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Private'), 1, 0, 0),
(4, 'Tolowa Dee-ni'' Nation', 'Tolowa Dee-ni'' Nation', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Federally Recognized Indian Tribe'), 1, 0, 0),
(4, 'Transportation & Public Works / Dept. of Emergency Management', 'Transportation & PW / Dept of Emergency Management', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Local Agency'), 1, 0, 0),
(4, 'Travis Ranch LLC', 'Travis Ranch LLC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Private'), 1, 0, 0),
(4, 'Trinity County Fire Safe Council', 'Trinity County FSC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Safe Council'), 1, 0, 0),
(4, 'Trinity Timberlands LLC', 'Trinity Timberlands LLC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Private'), 1, 0, 0),
(4, 'Upper Mark West Fire Safe Council', 'Upper Mark West FSC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Safe Council'), 1, 0, 0),
(4, 'Wagner Land Company', 'Wagner Land Company', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Private'), 1, 0, 0),
(4, 'Weed City Volunteer Fire Department', 'Weed City Volunteer Fire Department', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Protection District/ Fire District'), 1, 0, 0),
(4, 'Western Klamath Restoration Partnership', 'Western Klamath Restoration Partnership', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Other'), 1, 0, 0),
(4, 'Western Rivers Conservancy', 'Western Rivers Conservancy', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Non-Profit Organization'), 1, 0, 0),
(4, 'Willits Fire', 'Willits Fire', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Protection District/ Fire District'), 1, 0, 0),
(4, 'Westport Municipal Advisory Council', 'Westport Municipal Advisory Council', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Other'), 1, 0, 0),
(4, 'Westport Volunteer Fire Department', 'Westport Volunteer Fire Department', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Protection District/ Fire District'), 1, 0, 0),
(4, 'Yreka Area Fire Safe Council', 'Yreka Area FSC', (select OrganizationTypeID from dbo.OrganizationType where TenantID = 4 and OrganizationTypeName = 'Fire Safe Council'), 1, 0, 0)