/*

	select * from dbo.Tenant where TenantID = 14
	select * from ProjectFirma.dbo.Organization where TenantID = 14
	select * from ProjectFirma.dbo.OrganizationType where TenantID = 14

*/

--TODO: KeystoneOrganizationGuid?
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, '2nd Nature, LLC', '2N', 1, 'https://www.2ndnaturewater.com/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Agency on Aging Area 4', 'AAA4', 1, 'https://agencyonaging4.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Alpine Biomass Collaborative', 'ABC', 1, 'https://alpinebiomasscommittee.wordpress.com/', 1126, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Alpine County', 'Alpine County', 1, 'https://www.alpinecountyca.gov/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Alpine County Fire Safe Council', 'Alpine County - FSC', 1, 'https://alpinefiresafecouncil.org/', 1123, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Alpine Meadows Ski Resort', 'Alpine Meadows', 1, 'https://www.visitrenotahoe.com/things-to-do/ski/ski-resorts/alpine-meadows/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Alpine Springs County Water District', 'Alpine - SCWD', 1, 'https://alpinesprings.org/home', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Alta Fire Protection District', 'Alta- FPD', 1, 'https://altavolunteerfirefighters.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Amador County', 'Amador County', 1, 'https://www.amadorgov.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Amador County Fire Protection District', 'Amador County - FPD', 1, 'https://www.amadorfire.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Amador County Fire Safe Council', 'Amador County - FSC', 1, 'https://www.amadorfiresafe.org/', 1123, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'American Forests', 'AF', 1, 'https://www.americanforests.org/', 1122, 1, 0


insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Ascent Environmental', 'AE', 1, 'https://ascent.inc/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Auburn City Fire Protection District', 'Auburn City - FPD', 1, 'https://www.auburn.ca.gov/159/Fire', 1121, 1, 0


insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Boreal', 'Boreal', 1, 'https://www.rideboreal.com/', 1119, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California Air Resources Board', 'CARB', 1, 'https://ww2.arb.ca.gov/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California Association of Resource Conservation Districts', 'CARCD', 1, 'https://carcd.org/', 1124, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California Central Valley Regional Water Quality Control Board', 'Central Valley WB', 1, 'https://www.waterboards.ca.gov/centralvalley/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California Conservation Corps.', 'CCC', 1, 'https://ccc.ca.gov/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California Department of Conservation', 'CA DOC', 1, 'https://www.conservation.ca.gov/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California Department of Fish and Wildlife', 'CDFW', 1, 'https://wildlife.ca.gov/Regions/2', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California Department of Forestry and Fire Protection', 'Cal Fire', 1, 'https://www.fire.ca.gov/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California Department of Housing and Community Development', 'California HCD', 1, 'https://www.hcd.ca.gov/', 1118, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California Department of Transportation', 'Caltrans', 1, 'https://dot.ca.gov/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California Department of Water Resources', 'California DWR', 1, 'https://water.ca.gov/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California Division of Boating and Waterways', 'California DBW', 1, 'http://www.dbw.ca.gov/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California Environmental Protection Agency', 'Cal EPA', 1, 'https://calepa.ca.gov/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California Fire Safe Council', 'CFSC', 1, 'https://cafiresafecouncil.org/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California Forestry Association', 'CalForest', 1, 'https://calforests.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California Lahontan Regional Water Quality Control Board', 'Lahontan WB', 1, 'https://www.waterboards.ca.gov/lahontan/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California Native Plant Society', 'CNPS', 1, 'https://www.cnps.org/', 1122, 1, 0
--insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California Native Plant Society', 'CNPS', 1, 'https://www.cnps.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California Natural Resources Agency', 'CNRA', 1, 'https://resources.ca.gov/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California Pines Community Services District', 'CPCSD', 1, 'https://cpcsd.specialdistrict.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California State Lands Commission', 'California SLC', 1, 'https://www.slc.ca.gov/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California State Transportation Agency', 'CalSTA', 1, 'https://calsta.ca.gov/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California State Water Resources Control Board', 'SWRCB', 1, 'https://www.waterboards.ca.gov/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California Strategic Growth Council', 'SGC', 1, 'https://sgc.ca.gov/', 1118, 1, 0
---insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California Tahoe Conservancy', 'CTC', 1, 'https://tahoe.ca.gov/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California Transportation Commission', 'Cal Trans Comm', 1, 'https://catc.ca.gov/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'California Wildlife Conservation Board', 'WCB', 1, 'https://wcb.ca.gov/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Camptonville Community Partnership', 'CCP', 1, 'https://www.facebook.com/theccp.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Camptonville Community Services District', 'CCSD', 1, 'https://www.camptonvilledistrict.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Carson City County', 'Carson', 1, 'https://www.carson.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Cave Rock General Improvement District', 'CRGID', 1, 'https://caverockgid.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'City of South Lake Tahoe', 'CSLT', 1, 'https://www.cityofslt.us/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'City of South Lake Tahoe Fire Department', 'CSLT FD', 1, 'https://www.cityofslt.us/384/Fire', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Clean Tahoe Program', 'Clean Tahoe', 1, 'https://www.clean-tahoe.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Clean up the Lake', 'Clean up the Lake', 1, 'https://cleanupthelake.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Colfax', 'Colfax', 1, 'https://colfax-ca.gov/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Colfax City Fire Dept.', 'Colfax City FD', 1, 'https://www.placer.ca.gov/7873/City-of-Colfax-Station-36', 1121, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Crystal Shores East Homeowners Association', 'CSEHOA', 1, 'https://www.nevada-homeowners-associations.com/nvboard_list.php?mastertable=nevada-hoa-p&masterkey1=C1454-1962', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Deer Creek Resources', 'DCR', 1, 'https://www.deercreekgis.com/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Desert Research Institute', 'DRI', 1, 'https://www.dri.edu/', 1120, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Diamond Peak', 'Diamond Peak', 1, 'https://www.diamondpeak.com/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Diamond Springs FPD', 'Diamond Springs FPD', 1, 'https://www.diamondfire.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Dobbins Oregon House Fire Dsitrict', 'DOHFD', 1, 'http://www.dohfd.com/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Douglas County', 'Douglas County', 1, 'https://www.douglascountynv.gov/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Douglas County Sewer Improvement District', 'DCSID', 1, 'https://dcltsa.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Downieville Fire Protection District', 'Downieville - FPD', 1, 'https://downievillefire.specialdistrict.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'ECO-CLEAN Solutions', 'ECO', 1, 'https://www.eco-cleansolutions.com/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Edgewood Companies', 'Edgewood', 1, 'https://edgewoodcompanies.com/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'El Dorado County', 'El Dorado County', 1, 'https://www.edcgov.us/', 1121, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'El Dorado County Fire Protection District ', 'El Dorado County - FPD', 1, 'https://www.eldoradocountyfire.com/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'El Dorado County Fire Safe Council', 'El Dorado County- FSC', 1, 'https://www.edcfiresafe.org/', 1123, 1, 0


insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'El Dorado Irrigation District', 'El Dorado County - ID', 1, 'https://www.eid.org/', 1121, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Eldorado County Air Pollution Control District', 'El Dorado County - APCD', 1, 'https://www.edcgov.us/airqualitymanagement', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Elk Point Country Club Homeowners'' Association', 'Elk Point HOA', 1, '', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Environmental Incentives', 'EI', 1, 'https://enviroincentives.com/', 1119, 1, 0
--insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'ESA Sitka', 'ESA', 1, 'https://esassoc.com/about/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Fallen Leaf Fire Department', 'Fallen Leaf FD', 1, 'https://fllcsd.org/fire-department/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Feather River Air Quality Management District', 'Feather River - AQMD', 1, 'https://www.fraqmd.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Feather River Recreation and Park District', 'Feather River - RPD', 1, 'https://www.frrpd.com/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Federal Emergency Management Agency', 'FEMA', 1, 'https://www.fema.gov/', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Foresthill Fire Protection District', 'Foresthill - FPD', 1, 'https://www.foresthillfire.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Foresthill Public Utility District', 'Foresthill - PUD', 1, 'https://www.foresthillpud.com/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Friends of Ski Run', 'Friends', 1, '', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Garden Valley Fire Protection District', 'Garden Valley - FPD', 1, 'https://www.gardenvalley.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Georgetown Divide Public Utility District', 'Georgetown Divide - PUD', 1, 'https://www.gd-pud.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Georgetown Divide RCD', 'Georgetown Divide - RCD', 1, 'https://www.edlafco.us/georgetown-divide-rcd', 1124, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Georgetown Divide Recreation District', 'Georgetown Divide - RD', 1, 'https://www.gdrd.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Georgetown Fire Protection District', 'Georgetown- FPD', 1, 'https://www.geofire.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Glenbrook Homeowners Association', 'GHOA', 1, 'https://glenbrooktahoe.org/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Glenbrook Underground, Inc', 'GU', 1, 'https://sites.google.com/glenbrookunderground.org/gbu/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Granlibakken', 'Granlibakken ', 1, 'https://www.granlibakken.com/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Grass Valley', 'Grass Valley', 1, 'https://www.cityofgrassvalley.com/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Grass Valley Fire Department', 'Grass Valley - FD', 1, 'https://www.cityofgrassvalley.com/fire-department', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Grizzly Flats Community Services District', 'Grizzly Flats CSD', 1, 'https://grizzlyflatscsd.com/?page_id=2', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Heavenly Ski Resort', 'Heavenly ', 1, 'https://www.skiheavenly.com/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Higgins Fire Protection District', 'Higgins - FPD', 1, 'https://www.higginsfire.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Homewood Ski Resort', 'Homewood ', 1, 'https://www.skihomewood.com/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Humboldt State University', 'Humboldt', 1, 'https://www.humboldt.edu/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Incline Village General Improvement District', 'IVGID', 1, 'https://www.yourtahoeplace.com/ivgid', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Ingersoll Timber Enterprises', 'Ingersoll Timber Enterprises', 1, '', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'KBM Enterprises', 'KBM', 1, 'https://www.kbm-inc.com/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Kirkwood', 'Kirkwood', 1, 'https://www.kirkwood.com/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Kirkwood Meadows PUD', 'Kirkwood Meadow - PUD', 1, 'https://www.kmpud.com/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Lake Tahoe Community College', 'LTCC', 1, 'https://ltcc.edu/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Lake Tahoe West', 'LTW', 1, 'https://tahoe.ca.gov/lake-tahoe-west/', 1126, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Lake Valley Fire Protection District', 'Lake Valley - FPD', 1, 'https://lakevalleyfire.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Lakeside Park Association', 'LPA', 1, 'https://lakesideparkassociation.org/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'League to Save Lake Tahoe / Keep Tahoe Blue', 'League to Save SLT', 1, 'https://www.keeptahoeblue.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Liberty Utilities', 'Liberty', 1, 'https://california.libertyutilities.com/truckee/residential', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Loma Rica Fire Protection District', 'Loma Rica - FPD', 1, 'http://www.lrbvfire.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Loyalton Fire Department', 'Loyalton - FD', 1, 'https://www.facebook.com/loyaltonfire/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Lukins Brothers Water Company, Inc.', 'Lukins Brothers', 1, 'https://lukinswater.com/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Marla Bay General Improvement District', 'MBGID', 1, 'https://ntcd.org/marla-bay/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Martis Camp Community Association', 'MCCA', 1, 'https://martiscamp.org/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Martis Fund', 'Martis Fund', 1, 'https://martisfund.org/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'McKinney Water District', 'MWD', 1, 'https://www.mckinneywaterdistrict.com/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Meeks Bay Fire Protection District', 'Meeks Bay - FPD', 1, 'https://www.meeksbayfire.com/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Middle Truckee River Watershed Forest Partnership ', 'MTRWFP', 1, 'https://www.truckeeforests.org/', 1126, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Mosquito Fire Protection District', 'Mosquito - FPD', 1, 'https://www.mfpd.us/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Mountain Communities Water Resources Association', 'MCWRA', 1, 'https://mountaincountieswater.com/', 1126, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'National Fish and Wildlife Foundation', 'NFWF', 1, 'https://www.nfwf.org/', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'National Forest Foundation', 'NFF', 1, 'https://www.nationalforests.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'National Park Service', 'NPS', 1, 'https://www.nps.gov/index.htm', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'National Science Foundation', 'NSF', 1, 'https://www.nsf.gov/', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'National Wild Turkey Federation', 'NWTF', 1, 'https://www.nwtf.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Nevada City', 'Nevada City', 1, 'https://www.nevadacityca.gov/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Nevada City Fire Department', 'Nevada City - FD', 1, 'https://www.nevadacityca.gov/pview.aspx?id=20712&catid=0', 1121, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Nevada County Consolidated Fire District', 'Nevada County - CFD', 1, 'https://www.nccfire.com/', 1121, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Nevada County Irrigation District', 'Nevada County - ID', 1, 'https://www.nidwater.com/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Nevada County Office of Emergency Services', 'Nevada County - OES', 1, 'https://www.nevadacountyca.gov/3453/Ready-Nevada-County', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Nevada County RCD', 'Nevada County - RCD', 1, 'https://www.ncrcd.org/', 1124, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Nevada Department of Transportation', 'NV DOT', 1, 'https://www.dot.nv.gov/', 1120, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Nevada Division of Environmental Protection', 'NDEP', 1, 'https://ndep.nv.gov/', 1120, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Nevada Division of Forestry', 'NV Forestry', 1, 'https://forestry.nv.gov/', 1120, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Nevada Division of Natural Heritage', 'NV Heritage', 1, 'https://heritage.nv.gov/', 1120, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Nevada Energy', 'NV Energy', 1, 'https://www.nvenergy.com/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Nevada Environmental Consulting', 'NVENV', 1, 'https://www.nvenv.net/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Nevada State Parks', 'NV Parks ', 1, 'https://parks.nv.gov/', 1120, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Nevada Tahoe Conservation District', 'NTCD', 1, 'https://ntcd.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Nevada Tahoe Resource Team', 'NTRT', 1, 'https://lands.nv.gov/resource-programs/tahoe', 1120, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Nevada Tahoe Resource Team - Nevada Department of Wildlife', 'NDOW', 1, '', 1120, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Nevada Tahoe Resource Team - Nevada Division of Forestry', 'NDF', 1, '', 1120, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Nevada Tahoe Resource Team - Nevada Division of State Lands', 'NDSL', 1, '', 1120, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Nevada Tahoe Resource Team - Nevada Division of State Parks', 'NV State Parks', 1, '', 1120, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Nisenan', 'Nisenan', 1, 'https://www.nisenan.org/', 1125, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'North Lake Tahoe Fire Protection District', 'North Lake Tahoe - FPD', 1, 'https://nltfpd.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'North San Juan Fire Protection District', 'North San Juan - FPD', 1, 'https://nsjfire.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'North Tahoe Community Alliance', 'NTCA', 1, 'https://www.northtahoecommunityalliance.com/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'North Tahoe Environmental Education Coalition', 'NTEEC', 1, '', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'North Tahoe Fire Protection District', 'North Tahoe - FPD', 1, 'https://www.ntfire.net/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'North Tahoe Public Utility District', 'NTPUD', 1, 'https://ntpud.org/', 1121, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Northern Sierra Air Quality Management District', 'Northern Sierra - AQMD', 1, 'https://myairdistrict.com/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Northstar', 'Northstar', 1, 'https://www.northstarcalifornia.com/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Northstar Community Services District', 'Northstar - CSD', 1, 'https://www.northstarcsd.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Northstar Fire Department', 'Northstar - FD', 1, '', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Olympic Valley Public Service District', 'Olympic Valley - PSD', 1, 'https://www.ovpsd.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Ophir Hill Fire Protection District', 'Ophir Hill - FPD', 1, 'http://www.ophirhillfire.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Pacific Crest Trail Association', 'PCTA', 1, 'https://www.pcta.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Palisades Tahoe', 'Palisades', 1, 'https://www.palisadestahoe.com/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Peardale-Chicago Park Fire Department', 'PCP - FD', 1, 'https://www.pcpfire.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Penn Valley Fire Protection District', 'Penn Valley - FPD', 1, 'https://pennvalleyfire.com', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'PG&E', 'PG&E', 1, 'https://www.pge.com/en.html', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Pioneer FPD', 'Pioneer - FPD', 1, 'https://www.pioneerfire.org/', 1121, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Placer County Air Pollution Control District', 'PCAPCD', 1, 'https://www.placerair.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Placer County Fire Department', 'Placer County - FD', 1, 'https://www.placer.ca.gov/7625/Fire-Department', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Placer County Fire Safe Alliance', 'Placer County - FSA', 1, 'https://www.placer.ca.gov/5721/Fire-Safe-Alliance', 1121, 1, 0


insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Placer Hills Fire Protection District', 'Placer Hills - FPD', 1, 'https://placerhillsfire.org/', 1121, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Placer Prescribed Burn Assoication', 'Placer - PBA', 1, 'https://placerrcd.org/projects/placer-prescribed-burn-association/', 1126, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Placerville', 'Placerville', 1, 'https://www.cityofplacerville.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Pliocene Ridge Community Services District', 'Pliocene Ridge -CSD', 1, 'https://www.plioceneridge.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Plumas County', 'Plumas County', 1, 'https://www.plumascounty.us/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Plumas County Fire Safe Council', 'Plumas County - FSC', 1, 'https://www.plumasfiresafe.org/', 1123, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Regional Transportation Commission of Washoe County', 'Washoe RTC', 1, 'https://rtcwashoe.com/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Rescue FPD', 'Rescue - FPD', 1, 'https://www.rescuefiredepartment.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Restoring the Lake Depths Foundation', 'RLDF', 1, 'https://restoremylake.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Rough & Ready Fire Department', 'RRFD', 1, 'https://www.facebook.com/rrvfd/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Round Hill General Improvement District', 'Round Hill - GID', 1, 'https://rhgid.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Royal Gorge Cross Country Resort', 'Royal Gorge Cross Country Resort', 1, 'https://www.royalgorge.com/home', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Sacramento Placerville Transportation Corridor Joint Powers Authority', 'SPTC-JPA', 1, 'https://sptc-jpa.org/index.html', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Sacramento Regional Conservation Corps', 'Sacramento - RCC', 1, 'https://www.saccorps.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Sierra At Tahoe', 'Sierra At Tahoe', 1, 'https://www.sierraattahoe.com/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Sierra Business Council', 'SBC', 1, 'https://www.sierrabusiness.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Sierra Buttes Trail Stewardship', 'Sierra Trails ', 1, 'https://sierratrails.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Sierra City Fire District', 'Sierra City - FPD', 1, '', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Sierra Club', 'Sierra Club', 1, 'https://www.sierraclub.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Sierra College', 'Sierra College', 1, 'https://www.sierracollege.edu/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Sierra County', 'Sierra County', 1, 'https://www.sierracounty.ca.gov/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Sierra County Fire Protection District', 'Sierra County - FPD', 1, 'https://www.sierracountyfireprotectiondistrict1.org/', 1121, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Sierra County Land Trust', 'Sierra County Land Trust', 1, 'https://www.sierracountylandtrust.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Sierra Forest Legacy', 'SFL', 1, 'https://sierraforestlegacy.org/', 1122, 1, 0


insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Sierra Nevada Alliance', 'SNA', 1, 'https://sierranevadaalliance.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Sierra Nevada Conservancy', 'SNC', 1, 'https://sierranevada.ca.gov/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Sierra Pacific Industries', 'SPI', 1, 'https://www.spi-ind.com/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Sierra Streams Institute', 'SSI', 1, 'https://sierrastreamsinstitute.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Sierra Water Workgroup', 'SWW', 1, 'http://www.sierrawaterworkgroup.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Siller Helicopters', 'SH', 1, 'https://sillerhelicopters.com/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Ski California', 'Ski California', 1, 'https://skicalifornia.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Ski Run Marina', 'Ski Run Marina', 1, 'https://skirunmarina.com/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Skyland General Improvement District', 'Skyland GID', 1, 'http://skylandgid.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Smartville Fire Protection District', 'Smartville - FPD', 1, 'https://www.smartsvillefire.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Soda Springs Mountain Resort', 'Soda Springs Mountain Resort', 1, 'https://www.skisodasprings.com/', 1119, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Soper-Wheeler', 'Soper-Wheeler', 1, 'http://www.soperwheeler.com/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Soroptimist International of South Lake Tahoe', 'SISLT', 1, 'https://www.sislt.org/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'South Lake Tahoe', 'SLT', 1, 'https://www.cityofslt.us/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'South Lake Tahoe Fire District', 'SLT- FD', 1, 'https://www.cityofslt.us/384/Fire', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'South Lake Tahoe Tourism Improvement District', 'SLTTID', 1, 'https://southtahoetourism.com/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'South Shore Transportation Management Association', 'SSTMA', 1, 'https://ss-tma.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'South Tahoe Environmental Education Coalition', 'STEEC', 1, 'https://steec.us/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'South Tahoe Public Utility District', 'STPUD', 1, 'https://stpud.us/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'South Tahoe Refuse Co., Inc', 'STR', 1, 'https://southtahoerefuse.com/', 1119, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Spatial Informatics Group', 'SIG', 1, 'https://sig-gis.com/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Sugar Bowl Resort', 'Sugar Bowl', 1, 'https://www.sugarbowl.com/home', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Sugar Pine Foundation', 'SPF', 1, 'https://sugarpinefoundation.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Tahoe Area Mountain Bike Association', 'TAMBA', 1, 'https://tamba.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Tahoe Backcountry Alliance', 'TBA', 1, 'https://tahoebackcountryalliance.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Tahoe City Marina', 'TCM', 1, 'https://tahoecitymarina.com/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Tahoe City Public Utility District', 'TCPUD', 1, 'https://www.tcpud.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Tahoe Donner Association', 'TDA', 1, 'https://www.tahoedonner.com/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Tahoe Douglas Fire Protection District', 'Tahoe Douglas - FPD', 1, 'https://tahoefire.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Tahoe Douglas Visitors Authority', 'TDVA', 1, 'https://tahoedouglasva.org/', 1122, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Tahoe Fund', 'Tahoe Fund', 1, 'https://www.tahoefund.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Tahoe Institute for Natural Science', 'TINS', 1, 'https://www.tinsweb.org/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Tahoe Keys Marina (Suntex)', 'TKM', 1, 'https://suntex.com/locations/marina-tahoe-keys/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Tahoe Keys Property Owners Association', 'TKPOA', 1, 'https://tkpoa.com/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Tahoe Lakefront Owners Association', 'TLOA', 1, 'https://www.tloa.net/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Tahoe Metropolitan Planning Organization', 'TMPO', 1, '', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Tahoe Mountain Resorts Foundation', 'TMRF', 1, 'https://www.tmrfoundation.com/', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Tahoe Prosperity Center', 'TPC', 1, 'https://tahoeprosperity.org/', 1122, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Tahoe Regional Planning Agency', 'TPRA', 1, 'https://www.trpa.gov/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Tahoe Rim Trail Association', 'TRTA', 1, 'https://tahoerimtrail.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Tahoe Science Advisory Council', 'TSAC', 1, 'https://www.tahoesciencecouncil.org/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Tahoe Science Consortium', 'TSC', 1, 'https://tahoescience.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Tahoe Transportation District', 'TTD', 1, 'https://www.tahoetransportation.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Tahoe Truckee Area Regional Transit', 'TART', 1, 'https://tahoetruckeetransit.com/', 1121, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Tahoe X/C', 'Tahoe X/C', 1, 'https://tahoexc.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'The CHY Company', 'CHY Company', 1, '', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'The Freshwater Trust', 'Freshwater Trust', 1, 'https://www.thefreshwatertrust.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'The Institute for Bird Populations', 'IBP', 1, 'https://www.birdpop.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'The Nature Conservancy', 'TNC', 1, 'https://www.nature.org/en-us/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'The Sierra Fund', 'Sierra Fund', 1, 'https://sierrafund.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Trout Unlimited', 'TU', 1, 'https://www.tu.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Truckee', 'Truckee', 1, 'https://www.townoftruckee.gov/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Truckee Donner Land Trust', 'Truckee Donner Land Trust', 1, 'https://www.truckeedonnerlandtrust.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Truckee Fire Protection District', 'Truckee - FPD', 1, 'https://www.truckeefire.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Truckee Meadows Water Authority', 'Truckee Meadows - WA', 1, 'https://tmwa.com/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Truckee River Fund/Community Foundation of Western Nevada', 'TRF/CFWN', 1, 'https://truckeeriverfund.org/', 1119, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Truckee Tahoe Airport District', 'TTAD', 1, 'https://truckeetahoeairport.com/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Truckee-Donner Recreation and Park District', 'TDRPD', 1, 'https://www.tdrpd.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'U.S. Army Corps of Engineers', 'USACOE', 1, 'https://www.usace.army.mil/', 1117, 1, 0
--insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'U.S. Bureau of Land Management', 'BLM', 1, 'https://www.blm.gov/', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'U.S. Bureau of Reclamation', 'USBOR', 1, 'https://www.usbr.gov/', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'U.S. Department of Agriculture', 'USDA', 1, 'https://www.usda.gov/', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'U.S. Department of Housing and Urban Development', 'HUD', 1, 'https://www.hud.gov/', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'U.S. Department of Transportation', 'US DOT', 1, 'https://www.transportation.gov/', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'U.S. Economic Development Administration', 'EDA', 1, 'https://www.eda.gov/', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'U.S. Environmental Protection Agency', 'USEPA', 1, 'https://www.epa.gov/', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'U.S. Federal Highway Administration', 'FHWA', 1, 'https://highways.dot.gov/', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'U.S. Federal Transit Administration', 'FTA', 1, 'https://www.transit.dot.gov/', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'U.S. Fish and Wildlife Service', 'USFWS', 1, 'https://www.fws.gov/', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'U.S. Forest Service - Lake Tahoe Basin Management Unit', 'USFS - LTBMU', 1, 'https://www.fs.usda.gov/ltbmu', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'U.S. Forest Service - Pacific Southwest Research Station', 'USFS - PSW', 1, 'https://www.fs.usda.gov/research/psw', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'U.S. Forest Service - Rocky Mountain Research Station', 'USFS - RMRS', 1, 'https://www.fs.usda.gov/research/rmrs', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'U.S. Geological Survey', 'USGS', 1, 'https://www.usgs.gov/', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'U.S. Natural Resource Conservation Service', 'NRCS', 1, 'https://www.nrcs.usda.gov/', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'UC Davis Tahoe Environmental Research Center', 'TERC', 1, 'https://tahoe.ucdavis.edu/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'United Auburn Indian Community (Miwok, Maidu)', 'Auburn Rancheria', 1, 'https://auburnrancheria.com/about-us/our-history-1/', 1125, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'University of CA Natural Reserve System - Sagehen Creek Field Station', 'Sagehen - UCNRS', 1, 'https://sagehen.ucnrs.org/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'University of California, Davis', 'UC Davis', 1, 'https://www.ucdavis.edu/', 1118, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'University of Nevada, Reno', 'UNR', 1, 'https://www.unr.edu/', 1120, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Unknown or Unspecified', 'UNKNOWN', 1, '', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'US Army Corps of Engineers ', 'USACOE', 1, 'https://www.spk.usace.army.mil/', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'US Burea of Reclamation (California Great Basin Region)', 'USBOR', 1, 'https://www.usbr.gov/mp/', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'US Bureau of Indian Affairs (Western Regional Office)', 'USBIA', 1, 'https://www.bia.gov/regional-offices/western', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'USFS Eldorado National Forest', 'USFS - ENF', 1, 'https://www.fs.usda.gov/eldorado/', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'USFS Plumas National Forest', 'USFS - PNF', 1, 'https://www.fs.usda.gov/plumas', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'USFS Tahoe National Forest', 'USFS - TNF', 1, 'https://www.fs.usda.gov/tahoe', 1117, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Vibrant Planet', 'VP', 1, 'https://www.vibrantplanet.net/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Washington Fire and Rescue', 'Washington- FR', 1, '', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Washoe County', 'Washoe County', 1, 'https://www.washoecounty.gov/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Washoe County Air Quality Management Division', 'WCAQ', 1, '', 1121, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Wildlands Network', 'WN', 1, 'https://www.wildlandsnetwork.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'YFR Tree & Land Management', 'YFR- TLM', 1, 'https://www.yubaforestrestoration.com/', 1119, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Yuba County', 'Yuba County', 1, 'https://www.yuba.org/', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Yuba County Public Works', 'Yuba County - PW', 1, 'https://www.yuba.org/departments/community_development/public_works/index.php', 1121, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Yuba County RCD', 'Yuba County - RCD', 1, 'https://www.yubarcd.org/', 1124, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Yuba Foothill Fire Protection District', 'Yuba Foothill - FPD', 1, '', 1121, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Yuba Watershed Institute', 'Yuba - WI', 1, 'https://yubawatershedinstitute.org/', 1122, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Yuba Watershed Protection & Firesafe Council', 'Yuba - WPFC', 1, 'https://yubafiresafe.org/', 1123, 1, 0
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) select 14, 'Yuba-Bear Burn Cooperative', 'Yuba - BBC', 1, 'https://www.yubabearburncoop.org/', 1126, 1, 0

--Naive match on Keystone Organization
update ProjectFirma.dbo.Organization
set KeystoneOrganizationGuid = ko.OrganizationGuid
from ProjectFirma.dbo.Organization pfo 
	join Keystone.dbo.Organization ko on ko.FullName = pfo.OrganizationName
where pfo.TenantID = 14
	and pfo.KeystoneOrganizationGuid is null

--Null out empty Organization values
update ProjectFirma.dbo.Organization
set OrganizationUrl = null
from ProjectFirma.dbo.Organization pfo 
where pfo.TenantID = 14
	and OrganizationUrl = ''

/* TEMPORARY? Organizations added for Funding Sources spreadsheet */
insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'American Recovery and Reinvestment Act', 'ARRA', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'Anonymous', 'Anonymous', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'Barton Health', 'Barton Health', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'Bella Vista', 'Bella Vista', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'Boatworks Mall- MJD Properties', 'BWKS', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'Butte County Fire Safe Council', 'Butte Fire Safe', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'California Energy Commission', 'CEC', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'California Governor''s Office of Planning and Research', 'California OPR', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'California State Coastal Conservancy', 'CSCC', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'California Fish Passage Forum', 'CFPF', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'California Wildlife Foundation', 'WF', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'Commercial Property Owners', 'Commercial', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'U.S. Department of Energy', 'DOE', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'Fee for Service', 'FFS', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'Headwaters', 'Headwaters', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'Hind Foundation', 'Hind', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'Integrated Watershed Restoration Program', 'IWRP', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'Lake Tahoe Visitors Authority', 'LTVA', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'Lakeside Marina', 'LM', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'Matching Funds Organization', 'Matching Funds', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'National Association of Conservation Districts', 'NACD', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'Nevada', 'NV', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'NOAA Restoration Center', 'NOAA', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'North Coast Resource Partnership', 'NCRP', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'Patagonia', 'Patagonia', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'Private', 'Private', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'Reno Midtown Rotary', 'RMR', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'Reno-Sparks Convention Center and Visitors Authority', 'RSCVA', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'Residential Property Owners', 'Residential', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'Resources Legacy Fund', 'RLF', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'South Tahoe Alliance of Resorts', 'STAR', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'South Tahoe Refuse', 'STR', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'Tahoe Blue Event Center', 'TBEC', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'Tahoe Water Suppliers Association', 'TWSA', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'The Glenbrook Project', 'The Glenbrook Project', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'U.S. Department of Agriculture - Agricultural Research Service', 'USDA ARS', 1, null, 1127, 1, 0

insert into ProjectFirma.dbo.Organization (TenantID, OrganizationName, OrganizationShortName, IsActive, OrganizationUrl, OrganizationTypeID, UseOrganizationBoundaryForMatchmaker, IsUnknownOrUnspecified) 
select 14, 'U.S. Forest Service', 'USFS', 1, null, 1127, 1, 0

/*

	select * from ProjectFirma.dbo.Organization
	where TenantID = 14
	order by OrganizationID

*/
