USE [ProjectFirma]
GO

/****** Object:  Table [dbo].[gt_pk_metadata]    Script Date: 5/17/2024 4:03:53 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[gt_pk_metadata](
	[table_schema] [nvarchar](128) NOT NULL,
	[table_name] [nvarchar](128) NOT NULL,
	[pk_column] [nvarchar](128) NOT NULL,
	[pk_column_idx] [int] NULL,
	[pk_policy] [varchar](32) NULL,
	[pk_sequence] [varchar](64) NULL,
 CONSTRAINT [UQ__gt_pk_me__E9F04F8925D771EB] UNIQUE NONCLUSTERED 
(
	[table_schema] ASC,
	[table_name] ASC,
	[pk_column] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[gt_pk_metadata]  WITH CHECK ADD  CONSTRAINT [CK__gt_pk_met__pk_po__33EB5ADF] CHECK  (([pk_policy]='autogenerated' OR [pk_policy]='assigned' OR [pk_policy]='sequence'))
GO

ALTER TABLE [dbo].[gt_pk_metadata] CHECK CONSTRAINT [CK__gt_pk_met__pk_po__33EB5ADF]
GO


INSERT INTO [dbo].[gt_pk_metadata]
           ([table_schema]
           ,[table_name]
           ,[pk_column]
           ,[pk_column_idx]
           ,[pk_policy]
           ,[pk_sequence])
     VALUES
           ('dbo', 'vGeoServerGeospatialArea', 'PrimaryKey', 1, 'autogenerated', NULL),
		   ('dbo', 'vGeoServerProjectDetailedLocations', 'PrimaryKey', 1, 'autogenerated', NULL),
           ('dbo', 'vGeoServerProjectSimpleLocations', 'PrimaryKey', 1, 'autogenerated', NULL)