insert into dbo.FirmaPageType(FirmaPageTypeID, FirmaPageTypeName, FirmaPageTypeDisplayName, FirmaPageRenderTypeID)
values
(45, 'ProposeProjectInstructions', 'Propose Project Instructions', 2)

insert into dbo.FirmaPage (TenantID, FirmaPageTypeID, FirmaPageContent)
values
(1, 45, '<p>This Proposed Project area of the RCD Project Tracker Project Tracker walks you through developing a project proposal.</p><p>The various aspects of your project that must be included in a project proposal can be seen on the left. Several of these sections are optional, but others are required:</p><ul><li><strong>Basics:</strong>&nbsp;You must enter the project''s estimated start and completion dates and estimated costs.</li><li><strong>Location:</strong>&nbsp;You must input your project''s location via an interactive map or provide a short location description.</li><li><strong>Performance Measures:</strong>&nbsp;You must enter at least one expected Performance Measure, or provide a note why this information is not available.</li><li><strong>Project Themes</strong>&nbsp;You must enter at least one Project Themes that your project will attain or support, and provide a description of how it will do so.</li><li><strong>Assessment</strong>&nbsp;If this project has a component, you will be required to complete a questionnaire.</li></ul><p>Use the navigation to the left to view and enter your Proposed Project details. Be sure to click Save on each page. In order to Save your proposal you will be required to complete the required steps on any given section. Once all required sections are complete you may submit your proposal for review. You will see some icons next to some pages – here is what they mean:</p><ul><li>Required information has not been completely provided (you can''t submit this proposal)</li><li>Required information has been provided (you may submit this proposal)</li></ul><p>Submitting this update will notify the reviewer. After review, your proposal will either be approved, or the reviewer will contact you for follow up.</p><p>Click the icon to view field-specific help.</p>'),
(2, 45, '<p>This Proposed Project area of the RCD Project Tracker Project Tracker walks you through developing a project proposal.</p><p>The various aspects of your project that must be included in a project proposal can be seen on the left. Several of these sections are optional, but others are required:</p><ul><li><strong>Basics:</strong>&nbsp;You must enter the project''s estimated start and completion dates and estimated costs.</li><li><strong>Location:</strong>&nbsp;You must input your project''s location via an interactive map or provide a short location description.</li><li><strong>Performance Measures:</strong>&nbsp;You must enter at least one expected Performance Measure, or provide a note why this information is not available.</li><li><strong>Project Themes</strong>&nbsp;You must enter at least one Project Themes that your project will attain or support, and provide a description of how it will do so.</li><li><strong>Assessment</strong>&nbsp;If this project has a component, you will be required to complete a questionnaire.</li></ul><p>Use the navigation to the left to view and enter your Proposed Project details. Be sure to click Save on each page. In order to Save your proposal you will be required to complete the required steps on any given section. Once all required sections are complete you may submit your proposal for review. You will see some icons next to some pages – here is what they mean:</p><ul><li>Required information has not been completely provided (you can''t submit this proposal)</li><li>Required information has been provided (you may submit this proposal)</li></ul><p>Submitting this update will notify the reviewer. After review, your proposal will either be approved, or the reviewer will contact you for follow up.</p><p>Click the icon to view field-specific help.</p>'),
(3, 45, '<p>This Proposed Project area of the RCD Project Tracker Project Tracker walks you through developing a project proposal.</p><p>The various aspects of your project that must be included in a project proposal can be seen on the left. Several of these sections are optional, but others are required:</p><ul><li><strong>Basics:</strong>&nbsp;You must enter the project''s estimated start and completion dates and estimated costs.</li><li><strong>Location:</strong>&nbsp;You must input your project''s location via an interactive map or provide a short location description.</li><li><strong>Performance Measures:</strong>&nbsp;You must enter at least one expected Performance Measure, or provide a note why this information is not available.</li><li><strong>Project Themes</strong>&nbsp;You must enter at least one Project Themes that your project will attain or support, and provide a description of how it will do so.</li><li><strong>Assessment</strong>&nbsp;If this project has a component, you will be required to complete a questionnaire.</li></ul><p>Use the navigation to the left to view and enter your Proposed Project details. Be sure to click Save on each page. In order to Save your proposal you will be required to complete the required steps on any given section. Once all required sections are complete you may submit your proposal for review. You will see some icons next to some pages – here is what they mean:</p><ul><li>Required information has not been completely provided (you can''t submit this proposal)</li><li>Required information has been provided (you may submit this proposal)</li></ul><p>Submitting this update will notify the reviewer. After review, your proposal will either be approved, or the reviewer will contact you for follow up.</p><p>Click the icon to view field-specific help.</p>')


