drop table dbo.PerformanceMeasureExpectedSubcategoryOptionProposed
drop table dbo.NotificationProposedProject
drop table dbo.PerformanceMeasureExpectedProposed
drop table dbo.ProposedProjectAssessmentQuestion
drop table dbo.ProposedProjectClassification
drop table dbo.ProposedProjectImage
drop table dbo.ProposedProjectLocation
drop table dbo.ProposedProjectLocationStaging
drop table dbo.ProposedProjectNote
drop table dbo.ProposedProjectOrganization
drop table dbo.ProposedProjectWatershed
drop table dbo.ProposedProject

Alter Table dbo.Project Drop Column ProposedProjectID
Alter Table dbo.PerformanceMeasureExpected Drop Column PerformanceMeasureExpectedProposedID