exec sp_rename 'dbo.AK_TaxonomyTierTwo_TaxonomyTierTwoName_TenantID', 'AK_TaxonomyBranch_TaxonomyBranchName_TenantID', 'OBJECT';
exec sp_rename 'dbo.PK_TaxonomyTierTwo_TaxonomyTierTwoID', 'PK_TaxonomyBranch_TaxonomyBranchID', 'OBJECT';
exec sp_rename 'dbo.AK_TaxonomyTierTwo_TaxonomyTierTwoID_TenantID', 'AK_TaxonomyBranch_TaxonomyBranchID_TenantID', 'OBJECT';
exec sp_rename 'dbo.FK_TaxonomyTierTwo_Tenant_TenantID', 'FK_TaxonomyBranch_Tenant_TenantID', 'OBJECT';
exec sp_rename 'dbo.FK_TaxonomyTierTwoPerformanceMeasure_TaxonomyTierTwo_TaxonomyTierTwoID', 'FK_TaxonomyBranchPerformanceMeasure_TaxonomyBranch_TaxonomyBranchID', 'OBJECT';
exec sp_rename 'dbo.FK_TaxonomyTierTwoPerformanceMeasure_TaxonomyTierTwo_TaxonomyTierTwoID_TenantID', 'FK_TaxonomyBranchPerformanceMeasure_TaxonomyBranch_TaxonomyBranchID_TenantID', 'OBJECT';
exec sp_rename 'dbo.FK_TaxonomyLeaf_TaxonomyTierTwo_TaxonomyTierTwoID', 'FK_TaxonomyLeaf_TaxonomyBranch_TaxonomyBranchID', 'OBJECT';
exec sp_rename 'dbo.FK_TaxonomyLeaf_TaxonomyTierTwo_TaxonomyTierTwoID_TenantID', 'FK_TaxonomyLeaf_TaxonomyBranch_TaxonomyBranchID_TenantID', 'OBJECT';
exec sp_rename 'dbo.FK_TaxonomyTierTwo_TaxonomyTrunk_TaxonomyTrunkID_TenantID', 'FK_TaxonomyBranch_TaxonomyTrunk_TaxonomyTrunkID_TenantID', 'OBJECT';
exec sp_rename 'dbo.FK_TaxonomyTierTwo_TaxonomyTrunk_TaxonomyTrunkID', 'FK_TaxonomyBranch_TaxonomyTrunk_TaxonomyTrunkID', 'OBJECT';
exec sp_rename 'dbo.FK_TaxonomyTierTwoPerformanceMeasure_PerformanceMeasure_PerformanceMeasureID', 'FK_TaxonomyBranchPerformanceMeasure_PerformanceMeasure_PerformanceMeasureID', 'OBJECT';
exec sp_rename 'dbo.FK_TaxonomyTierTwoPerformanceMeasure_PerformanceMeasure_PerformanceMeasureID_TenantID', 'FK_TaxonomyBranchPerformanceMeasure_PerformanceMeasure_PerformanceMeasureID_TenantID', 'OBJECT';
exec sp_rename 'dbo.PK_TaxonomyTierTwoPerformanceMeasure_TaxonomyTierTwoPerformanceMeasureID', 'PK_TaxonomyBranchPerformanceMeasure_TaxonomyBranchPerformanceMeasureID', 'OBJECT';
exec sp_rename 'dbo.AK_TaxonomyTierTwoPerformanceMeasure_TaxonomyTierTwoID_PerformanceMeasureID', 'AK_TaxonomyBranchPerformanceMeasure_TaxonomyBranchID_PerformanceMeasureID', 'OBJECT';
exec sp_rename 'dbo.FK_TaxonomyTierTwoPerformanceMeasure_Tenant_TenantID', 'FK_TaxonomyBranchPerformanceMeasure_Tenant_TenantID', 'OBJECT';
exec sp_rename 'dbo.TaxonomyLeaf.TaxonomyTierTwoID', 'TaxonomyBranchID', 'COLUMN';
exec sp_rename 'dbo.TaxonomyTierTwo.TaxonomyTierTwoCode', 'TaxonomyBranchCode', 'COLUMN';
exec sp_rename 'dbo.TaxonomyTierTwo.TaxonomyTierTwoDescription', 'TaxonomyBranchDescription', 'COLUMN';
exec sp_rename 'dbo.TaxonomyTierTwo.TaxonomyTierTwoID', 'TaxonomyBranchID', 'COLUMN';
exec sp_rename 'dbo.TaxonomyTierTwo.TaxonomyTierTwoName', 'TaxonomyBranchName', 'COLUMN';
exec sp_rename 'dbo.TaxonomyTierTwoPerformanceMeasure.IsPrimaryTaxonomyTierTwo', 'IsPrimaryTaxonomyBranch', 'COLUMN';
exec sp_rename 'dbo.TaxonomyTierTwoPerformanceMeasure.TaxonomyTierTwoID', 'TaxonomyBranchID', 'COLUMN';
exec sp_rename 'dbo.TaxonomyTierTwoPerformanceMeasure.TaxonomyTierTwoPerformanceMeasureID', 'TaxonomyBranchPerformanceMeasureID', 'COLUMN';
exec sp_rename 'dbo.TaxonomyTierTwo', 'TaxonomyBranch';
exec sp_rename 'dbo.TaxonomyTierTwoPerformanceMeasure', 'TaxonomyBranchPerformanceMeasure';