Update dbo.ProjectUpdateConfiguration
Set ProjectUpdateKickOffIntroContent = '<p>It is officially reporting season! During this time we ask you to take a few minutes to update your project information in the Project Tracker to include accomplishments and expenditures. Please also upload any &quot;before,&quot; &quot;after,&quot;&nbsp;or &quot;during&quot;&nbsp;photos. Remember, photos are important for telling the story as well as great looking Project Fact Sheets!</p>  <p>We will be reviewing and approving updates throughout the reporting season. You will continue to receive these periodic reminder emails until you submit updates for all the projects listed above.</p>  <p>We greatly appreciate you taking the time to provide the Region with this important information. This reporting exercise helps us provide transparency to the public, show progress to all funders and interested stakeholders, and demonstrate the collective impact of your work.</p>'

Update dbo.ProjectUpdateConfiguration
Set ProjectUpdateReminderIntroContent = '<p>Please take a few minutes to update your project information in the Project Tracker to include accomplishments and expenditures. Please also upload any &quot;before,&quot; &quot;after,&quot;&nbsp;or &quot;during&quot;&nbsp;photos.&nbsp;Remember, photos are important for telling the story as well as great looking Project Fact Sheets!</p>  <p>We will be reviewing and approving updates throughout the reporting season. You will continue to receive these periodic reminder emails until you submit updates for all the projects listed above.</p>  <p>We greatly appreciate you taking the time to provide the Region with this important information. This reporting exercise helps us provide transparency to the public, show progress to all funders and interested stakeholders, and demonstrate the collective impact of your work.</p>'

Update dbo.ProjectUpdateConfiguration
Set ProjectUpdateCloseOutIntroContent = '<p>Today is the last day of reporting season. Thank you for updating your projects to reflect the most recent available information. If you have not already done so, please take a few minutes to update your project information in the Project Tracker to include accomplishments and expenditures. Please also upload any &quot;before,&quot; &quot;after,&quot;&nbsp;or &quot;during&quot;&nbsp;photos. Remember, photos are important for telling the story as well as great looking Project Fact Sheets!</p>  <p>We will be reviewing and approving updates throughout the reporting season. You will continue to receive these periodic reminder emails until you submit updates for all the projects listed above.</p>  <p>We greatly appreciate you taking the time to provide the Region with this important information. This reporting exercise helps us provide transparency to the public, show progress to all funders and interested stakeholders, and demonstrate the collective impact of your work.</p>'

Update dbo.FirmaPage
set FirmaPageContent = '<p>Projects in the Planning/Design, Implementation, and Post-Implementation stages should be reviewed and updated annually to ensure a complete and accurate project record. Administrators can configure a schedule for the project tracker to email the project primary contacts with a request to update projects.</p><ul><li>Use the&nbsp;<strong>Configure Notifications</strong>&nbsp;panel to enable project update notification emails and customize the email content and schedule</li><li>Use the&nbsp;<strong>Primary Contacts Receiving Notification</strong>&nbsp;panel to understand which users will be receiving reminders, and the status of their updates for the current reporting year</li><li>Use the&nbsp;<strong>Project Update Status</strong>&nbsp;panel to see a list of all projects which should receive an annual update</li></ul>'
where FirmaPageTypeID = 41