import { IEventSystem } from "../../ts-common/events";
import { View } from "../../ts-common/view";
import { Selection, TreeCollection, DataEvents, DragEvents, IDataEventsHandlersMap, IDragEventsHandlersMap } from "../../ts-data";
import { IEditorConfig } from "./Editor";
import { Id, ITree, ITreeConfig, ITreeState, TreeEvents, ITreeEventHandlersMap, ITreeItem } from "./types";
export declare class Tree<T extends object = object> extends View implements ITree {
    config: ITreeConfig;
    data: TreeCollection<T & ITreeItem>;
    events: IEventSystem<DataEvents | TreeEvents | DragEvents, IDataEventsHandlersMap & ITreeEventHandlersMap & IDragEventsHandlersMap>;
    selection: Selection;
    private _editor;
    private _handlers;
    private _isSelectionActive;
    private _root;
    private _focusId;
    constructor(element: HTMLElement | string, config?: ITreeConfig);
    focusItem(id: string): void;
    destructor(): void;
    editItem(id: string, config?: IEditorConfig): void;
    getState(): ITreeState;
    setState(state: ITreeState): void;
    toggle(id: Id): void;
    getChecked(): Id[];
    checkItem(id: Id): void;
    collapse(id: Id): void;
    collapseAll(): void;
    expand(id: Id): void;
    expandAll(): void;
    uncheckItem(id: Id): void;
    close(id: Id): void;
    closeAll(): void;
    open(id: Id): void;
    openAll(): void;
    unCheckItem(id: Id): void;
    private _draw;
    private _initEvents;
    private _initHandlers;
    private _drawItems;
    private _updateItemCheck;
    private _updateParents;
}
