SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LTInfoArea](
	[LTInfoAreaID] [int] NOT NULL,
	[LTInfoAreaName] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[LTInfoAreaDisplayName] [varchar](40) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[SortOrder] [int] NOT NULL,
 CONSTRAINT [PK_LTInfoArea_LTInfoAreaID] PRIMARY KEY CLUSTERED 
(
	[LTInfoAreaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_LTInfoArea_LTInfoAreaDisplayName] UNIQUE NONCLUSTERED 
(
	[LTInfoAreaDisplayName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_LTInfoArea_LTInfoAreaName] UNIQUE NONCLUSTERED 
(
	[LTInfoAreaName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
