SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ProjectTag](
	[ProjectTagID] [int] IDENTITY(1,1) NOT NULL,
	[ProjectID] [int] NOT NULL,
	[TagID] [int] NOT NULL,
 CONSTRAINT [PK_ProjectTag_ProjectTagID] PRIMARY KEY CLUSTERED 
(
	[ProjectTagID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_ProjectTag_ProjectID_TagID] UNIQUE NONCLUSTERED 
(
	[ProjectID] ASC,
	[TagID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[ProjectTag]  WITH CHECK ADD  CONSTRAINT [FK_ProjectTag_Project_ProjectID] FOREIGN KEY([ProjectID])
REFERENCES [dbo].[Project] ([ProjectID])
GO
ALTER TABLE [dbo].[ProjectTag] CHECK CONSTRAINT [FK_ProjectTag_Project_ProjectID]
GO
ALTER TABLE [dbo].[ProjectTag]  WITH CHECK ADD  CONSTRAINT [FK_ProjectTag_Tag_TagID] FOREIGN KEY([TagID])
REFERENCES [dbo].[Tag] ([TagID])
GO
ALTER TABLE [dbo].[ProjectTag] CHECK CONSTRAINT [FK_ProjectTag_Tag_TagID]