SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ThresholdRole](
	[ThresholdRoleID] [int] NOT NULL,
	[ThresholdRoleName] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ThresholdRoleDisplayName] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ThresholdRoleDescription] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LTInfoAreaID] [int] NOT NULL,
 CONSTRAINT [PK_ThresholdRole_ThresholdRoleID] PRIMARY KEY CLUSTERED 
(
	[ThresholdRoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_ThresholdRole_ThresholdRoleDisplayName] UNIQUE NONCLUSTERED 
(
	[ThresholdRoleDisplayName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_ThresholdRole_ThresholdRoleName] UNIQUE NONCLUSTERED 
(
	[ThresholdRoleName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[ThresholdRole]  WITH CHECK ADD  CONSTRAINT [FK_ThresholdRole_LTInfoArea_LTInfoAreaID] FOREIGN KEY([LTInfoAreaID])
REFERENCES [dbo].[LTInfoArea] ([LTInfoAreaID])
GO
ALTER TABLE [dbo].[ThresholdRole] CHECK CONSTRAINT [FK_ThresholdRole_LTInfoArea_LTInfoAreaID]