SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FocusArea](
	[FocusAreaID] [int] IDENTITY(1,1) NOT NULL,
	[FocusAreaNumber] [tinyint] NOT NULL,
	[FocusAreaName] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[FocusAreaDescription] [dbo].[html] NULL,
	[FocusAreaColor] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [PK_FocusArea_FocusAreaID] PRIMARY KEY CLUSTERED 
(
	[FocusAreaID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_FocusArea_FocusAreaName] UNIQUE NONCLUSTERED 
(
	[FocusAreaName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_FocusArea_FocusAreaNumber] UNIQUE NONCLUSTERED 
(
	[FocusAreaNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[FocusArea]  WITH CHECK ADD  CONSTRAINT [CK_FocusArea_FocusAreaNumberBetween1And99] CHECK  (([FocusAreaNumber]>=(1) AND [FocusAreaNumber]<=(99)))
GO
ALTER TABLE [dbo].[FocusArea] CHECK CONSTRAINT [CK_FocusArea_FocusAreaNumberBetween1And99]