SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[gt_pk_metadata](
	[table_schema] [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[table_name] [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[pk_column] [nvarchar](128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[pk_column_idx] [int] NULL,
	[pk_policy] [varchar](32) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[pk_sequence] [varchar](64) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
 CONSTRAINT [UQ__gt_pk_me__E9F04F8925D771EB] UNIQUE NONCLUSTERED 
(
	[table_schema] ASC,
	[table_name] ASC,
	[pk_column] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[gt_pk_metadata]  WITH CHECK ADD  CONSTRAINT [CK__gt_pk_met__pk_po__33EB5ADF] CHECK  (([pk_policy]='autogenerated' OR [pk_policy]='assigned' OR [pk_policy]='sequence'))
GO
ALTER TABLE [dbo].[gt_pk_metadata] CHECK CONSTRAINT [CK__gt_pk_met__pk_po__33EB5ADF]