SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LTInfoRole](
	[LTInfoRoleID] [int] NOT NULL,
	[LTInfoRoleName] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[LTInfoRoleDisplayName] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[LTInfoRoleDescription] [varchar](255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[LTInfoAreaID] [int] NOT NULL,
 CONSTRAINT [PK_LTInfoRole_LTInfoRoleID] PRIMARY KEY CLUSTERED 
(
	[LTInfoRoleID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_LTInfoRole_LTInfoRoleDisplayName] UNIQUE NONCLUSTERED 
(
	[LTInfoRoleDisplayName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_LTInfoRole_LTInfoRoleName] UNIQUE NONCLUSTERED 
(
	[LTInfoRoleName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[LTInfoRole]  WITH CHECK ADD  CONSTRAINT [FK_LTInfoRole_LTInfoArea_LTInfoAreaID] FOREIGN KEY([LTInfoAreaID])
REFERENCES [dbo].[LTInfoArea] ([LTInfoAreaID])
GO
ALTER TABLE [dbo].[LTInfoRole] CHECK CONSTRAINT [FK_LTInfoRole_LTInfoArea_LTInfoAreaID]