SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AccelaCAPRecordStatus](
	[AccelaCAPRecordStatusID] [int] NOT NULL,
	[AccelaCAPRecordStatusName] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[AccelaCAPRecordStatusDisplayName] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
 CONSTRAINT [PK_AccelaCAPRecordStatus_AccelaCAPRecordStatusID] PRIMARY KEY CLUSTERED 
(
	[AccelaCAPRecordStatusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_AccelaCAPRecordStatus_AccelaCAPRecordStatusDisplayName] UNIQUE NONCLUSTERED 
(
	[AccelaCAPRecordStatusDisplayName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_AccelaCAPRecordStatus_AccelaCAPRecordStatusName] UNIQUE NONCLUSTERED 
(
	[AccelaCAPRecordStatusName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
