SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LandBank](
	[LandBankID] [int] IDENTITY(1,1) NOT NULL,
	[LeadAgencyID] [int] NOT NULL,
	[ParcelID] [int] NOT NULL,
 CONSTRAINT [PK_LandBank_LandBankID] PRIMARY KEY CLUSTERED 
(
	[LandBankID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_LandBank_LeadAgencyID] UNIQUE NONCLUSTERED 
(
	[LeadAgencyID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[LandBank]  WITH CHECK ADD  CONSTRAINT [FK_LandBank_LeadAgency_LeadAgencyID] FOREIGN KEY([LeadAgencyID])
REFERENCES [dbo].[LeadAgency] ([LeadAgencyID])
GO
ALTER TABLE [dbo].[LandBank] CHECK CONSTRAINT [FK_LandBank_LeadAgency_LeadAgencyID]
GO
ALTER TABLE [dbo].[LandBank]  WITH CHECK ADD  CONSTRAINT [FK_LandBank_Parcel_ParcelID] FOREIGN KEY([ParcelID])
REFERENCES [dbo].[Parcel] ([ParcelID])
GO
ALTER TABLE [dbo].[LandBank] CHECK CONSTRAINT [FK_LandBank_Parcel_ParcelID]