SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ParcelGeometry](
	[Ogr_Geometry] [geometry] NOT NULL,
	[ParcelNumber] [varchar](30) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ParcelID] [int] NULL,
	[ParcelGeometryID] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_ParcelGeometry_ParcelGeometryID] PRIMARY KEY CLUSTERED 
(
	[ParcelGeometryID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
ALTER TABLE [dbo].[ParcelGeometry]  WITH CHECK ADD  CONSTRAINT [FK_ParcelGeometry_Parcel_ParcelID] FOREIGN KEY([ParcelID])
REFERENCES [dbo].[Parcel] ([ParcelID])
GO
ALTER TABLE [dbo].[ParcelGeometry] CHECK CONSTRAINT [FK_ParcelGeometry_Parcel_ParcelID]
GO
SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET NUMERIC_ROUNDABORT OFF

GO
CREATE SPATIAL INDEX [SPATIAL_ParcelGeometry_Ogr_Geometry] ON [dbo].[ParcelGeometry]
(
	[Ogr_Geometry]
)USING  GEOMETRY_AUTO_GRID 
WITH (BOUNDING_BOX =(-121, 38, -119, 40), 
CELLS_PER_OBJECT = 8, PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]