SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Snapshot](
	[SnapshotID] [int] IDENTITY(1,1) NOT NULL,
	[SnapshotDate] [date] NOT NULL,
	[SnapshotNote] [varchar](200) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[ProjectCount] [int] NOT NULL,
 CONSTRAINT [PK_Snapshot_SnapshotID] PRIMARY KEY CLUSTERED 
(
	[SnapshotID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [AK_Snapshot_SnapshotDate] UNIQUE NONCLUSTERED 
(
	[SnapshotDate] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
